Rewrite `lspkg` to Bourne POSIX (very incomplete)
Basic function right now, if it works at all. Still working on it.

diff --git a/lspkg b/lspkg
--- a/lspkg
+++ b/lspkg
@@ -1,9 +1,9 @@
-#!/bin/bash
+#!/bin/sh
 
 #----------------------------------------------------------------------------------
 # Project Name      - Extra/lspkg (List Packages)
 # Started On	    - Sun 17 Sep 04:13:30 BST 2017
-# Last Change       - Thu  5 Dec 16:46:42 GMT 2019
+# Last Change       - Thu  5 Dec 20:23:56 GMT 2019
 # Author E-Mail     - terminalforlife@yahoo.com
 # Author GitHub     - https://github.com/terminalforlife
 #----------------------------------------------------------------------------------
@@ -15,22 +15,22 @@ Progrm=${0##*/}
 #TODO - Add ability to search only the whole word, like `STRING`, not `*STRING*`.
 
 Err(){
-	printf "[L%0.4d] ERROR: %s\n" "$2" "$3" 1>&2
-	[ $1 -eq 1 ] && exit 1
+	printf "ERROR: %s\n" "$2" 1>&2
+	[ $1 -gt 0 ] && exit $1
 }
 
-Domain='https://github.com'
+StatusFile='/var/lib/dpkg/status'
 
 Usage(){
 	while read; do
 		printf "%s\n" "$REPLY"
 	done <<-EOF
-		            ${Progrm^^} ($CurVer)
+		            LSPKG ($CurVer)
 		            Written by terminalforlife (terminalforlife@yahoo.com)
 
 		            Search through, test for, and list out installed packages.
 
-		SYNTAX:     $Progrm [OPTS] [SEARCH_1] [SEARCH_2] [SEARCH_3] ...
+		SYNTAX:     $Progrm [OPTS] [SEARCH_1 [SEARCH_2] ...]
 
 		OPTS:       --help|-h|-?            - Displays this help information.
 		            --version|-v            - Output only the version datestamp.
@@ -39,13 +39,12 @@ Usage(){
 		            --name-only|-n          - Match only the package names.
 		            --ignore-case|-i        - Match both upper- and lower-case.
 		            --show-arch|-a          - Include package arch-types.
-		            --match-with T          - Where T is glob or the default, regex.
 		            --count|-c              - Display the total number of packages.
 
 		NOTE:       This shell program is only compatible with Debian or Ubuntu based
 		            systems, as it parses dpkg-query's output.
 
-		            Where SEARCH is an optional regex match of an installed package. By
+		            Where SEARCH is an optional glob match of an installed package. By
 		            default, the match will be looked for on the whole line, which includes
 		            the package name and its short description, like apt-cache search.
 
@@ -59,11 +58,9 @@ Usage(){
 
 		            An exit status of 4 means no match(es) were found.
 
-		SITE:       $Domain/terminalforlife/Extra
+		FILE:       $StatusFile
 	EOF
 }
-
-PACKNAME="{Package}"
 
 while [ "$1" ]; do
 	case $1 in
@@ -75,23 +72,15 @@ while [ "$1" ]; do
 		--debug|-D)
 			DebugMe='true' ;;
 		--no-describe|-N)
-			NO_DESCRIBE='true' ;;
+			NoDesc='true' ;;
 		--ignore-case|-i)
-			IGNORE_CASE='true' ;;
-		--match-with)
-			shift
-
-			if [[ $1 =~ ^(glob|regex)$ ]]; then
-				MATCH_WITH=$1
-			else
-				Err 1 $LINENO "Incorrect match type provided."
-			fi ;;
+			CaseInsensitive='true' ;;
 		--name-only|-n)
-			NAME_ONLY='true' ;;
+			NameOnly='true' ;;
 		--show-arch|-a)
-			PACKNAME="{Binary:Package}" ;;
+			ShowArch='true' ;;
 		--count|-c)
-			DOCOUNT='true' ;;
+			DOCount='true' ;;
 		-*)
 			Err 1 $LINENO "Incorrect argument(s) specified." ;;
 		*)
@@ -100,107 +89,109 @@ while [ "$1" ]; do
 	shift
 done
 
-PKG=($@)
-
-if ! type -fP dpkg-query > /dev/null 2>&1; then
-	Err 1 $LINENO "Dependency 'dpkg-query' not met."
-fi
-
 [ "$DebugMe" == 'true' ] && set -x
 
-PKG_LIST(){
-	if ! dpkg-query --show -f="\${db:Status-Abbrev} \$${PACKNAME} - \${binary:Summary}\n" \*; then
-		Err 1 $LINENO "Non-zero exit status for: dpkg-query"
-	fi
-}
+while read Key Value _; do
+	case $Key in
+		Package:)
+			while [ "$1" ]; do
+				case $1 in
+					"|$@") [ "$CurPKG" = "$Value" ] || continue 2
+				shift
+			done
 
-MATCH(){
-	SEARCH_RESULT+=1
+			Package=$Value ;;
+		Architecture:)
+			[ "$ShowArch" = 'true' ] && Arch=":$Value" ;;
+		Status:)
+			[ "$Value $_" = 'install ok installed' ] || continue ;;
+		Description:)
+			Desc="$Value $_" ;;
+		''|*)
+			continue ;;
+	esac
 
-	if ! [ "$NO_DESCRIBE" == 'true' ]; then
-		printf "%s\n" "$1"
-	else
-		printf "%s\n" "${1%% - *}"
-	fi
-}
-
-[ "$IGNORE_CASE" == 'true' ] && shopt -s nocaseglob
-
-declare -i COUNT=0
-declare -i SEARCH_RESULT=0
-while read -a X; do
-	if ! [ "$SHOWARCH" == 'true' ]; then
-		# Remove duplicate entries. This works because dpkg-query is outputting in
-		# alphabetical order, else this would surely be useless.
-		[ "${X[1]}" == "$OLD" ] && continue
+	if ! [ "$Package" = "$OldPackage" ]; then
+		printf "%s%s - %s\n" "$Package" "$Arch" "$Desc"
 	fi
 
-	if [ "${X[0]}" == "ii" ]; then
-		unset BUF
-		COUNT+=1
+	OldPackage=$Package
+done < "$StatusFile"
 
-		# No new line character as this is an array. Otherwise every word
-		# would print on a new line. The final new line is added when the
-		# text is displayed on the screen with echo.
-		printf -v BUF "%s " ${X[@]/ii}
-		[ "$BUF" ] || continue
-
-		# If there are user-specified matches to find, then iterate over
-		# them by checking to see if each current package matches each one
-		# in the list of ones the user specified.
-		if [ "${PKG[0]}" ]; then
-			USER_SEARCH='true'
-
-			for P in ${PKG[@]}; {
-				if [ "$NAME_ONLY" == 'true' ]; then
-					FILTER=" ${X[1]}"
-				else
-					FILTER=${X[@]/ii}
-				fi
-
-				case ${MATCH_WITH:-UNSET} in
-					glob)
-						if [[ $FILTER == " "$P ]]; then
-							MATCH "${BUF% }"
-						fi ;;
-					regex|*)
-						if [[ $FILTER =~ ${P/^/^ } ]]; then
-							MATCH "${BUF% }"
-						fi ;;
-				esac
-			}
-		else
-			# If there are no packages specified by the user, just show
-			# all of the packages. Removing the space because of the
-			# above printf command adding a trailing space.
-			if ! [ "$NO_DESCRIBE" == 'true' ]; then
-				printf "%s\n" "${BUF% }"
-			else
-				printf "%s\n" "${BUF%% - *}"
-			fi
-		fi
-
-		if ! [ "$SHOWARCH" == 'true' ]; then
-			# Save the current value to be checked when the next
-			# package is processed.
-			OLD=${X[1]}
-		fi
-	fi
-done <<< "$(PKG_LIST)"
-
-# Just in-case a later feature added below uses globs.
-[ "$IGNORE_CASE" == 'true' ] && shopt -u nocaseglob
-
-if [ "$DOCOUNT" == 'true' ]; then
-	if ! [ "$USER_SEARCH" == 'true' ]; then
-		printf "\nTOTAL: %'d\n" "$COUNT"
-	else
-		[ $SEARCH_RESULT -eq 0 ] && S= || S="\n"
-		printf "${S}TOTAL: %'d/%'d\n" "$SEARCH_RESULT" "$COUNT"
-	fi
-fi
-
-if [ "${PKG[*]}" -a ! $SEARCH_RESULT -gt 0 ]; then
-	exit 4
-fi
-
+#declare -i Count=0
+#declare -i SearchResult=0
+#while read -a CurLine; do
+#	if ! [ "$ShowArch" == 'true' ]; then
+#		# Remove duplicate entries. This works because dpkg-query is outputting in
+#		# alphabetical order, else this would surely be useless.
+#		[ "${CurLine[1]}" == "$Old" ] && continue
+#	fi
+#
+#	if [ "${CurLine[0]}" == "ii" ]; then
+#		unset Buffer
+#		Count+=1
+#
+#		# No new line character as this is an array. Otherwise every word
+#		# would print on a new line. The final new line is added when the
+#		# text is displayed on the screen with echo.
+#		printf -v Buffer "%s " ${CurLine[@]/ii}
+#		[ "$Buffer" ] || continue
+#
+#		# If there are user-specified matches to find, then iterate over
+#		# them by checking to see if each current package matches each one
+#		# in the list of ones the user specified.
+#		if [ -n "$1" ]; then
+#			USER_SEARCH='true'
+#
+#			for P in "$@"; {
+#				if [ "$NameOnly" == 'true' ]; then
+#					Filter=" ${CurLine[1]}"
+#				else
+#					Filter=${CurLine[@]/ii}
+#				fi
+#
+#				case ${MatchWith:-UNSET} in
+#					glob)
+#						if [[ $Filter == " "$P ]]; then
+#							Match "${Buffer% }"
+#						fi ;;
+#					regex|*)
+#						if [[ $Filter =~ ${P/^/^ } ]]; then
+#							Match "${Buffer% }"
+#						fi ;;
+#				esac
+#			}
+#		else
+#			# If there are no packages specified by the user, just show
+#			# all of the packages. Removing the space because of the
+#			# above printf command adding a trailing space.
+#			if ! [ "$NoDesc" == 'true' ]; then
+#				printf "%s\n" "${Buffer% }"
+#			else
+#				printf "%s\n" "${Buffer%% - *}"
+#			fi
+#		fi
+#
+#		if ! [ "$ShowArch" == 'true' ]; then
+#			# Save the current value to be checked when the next
+#			# package is processed.
+#			Old=${CurLine[1]}
+#		fi
+#	fi
+#done <<< "$(PKGList)"
+#
+## Just in-case a later feature added below uses globs.
+#[ "$CaseInsensitive" == 'true' ] && shopt -u nocaseglob
+#
+#if [ "$DOCount" == 'true' ]; then
+#	if ! [ "$USER_SEARCH" == 'true' ]; then
+#		printf "\nTOTAL: %'d\n" "$Count"
+#	else
+#		[ $SearchResult -eq 0 ] && S= || S="\n"
+#		printf "${S}TOTAL: %'d/%'d\n" "$SearchResult" "$Count"
+#	fi
+#fi
+#
+#if [ "$*" -a ! $SearchResult -gt 0 ]; then
+#	exit 4
+#fi
